version: '3.8'

services:
  backend:
    build:
      dockerfile: backend.Dockerfile
      context: ./backend
    volumes:
      - ./backend/app:/app/app
    container_name: flask-backend
    ports:
      - "5002:5002"
    networks:
      - network
    command: ["gunicorn", "-c", "gunicorn_config.py", "app:create_app()"]

  frontend:
    build:
      dockerfile: frontend.Dockerfile
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3001:3001"
    networks:
      - network
    command: ["npm", "run", "deploy"]

networks:
  network: