version: '3.8'

services:
  backend:
    build:
      dockerfile: backend/backend.Dockerfile
      context: .
    container_name: flask-backend
    ports:
      - "5002:5002"
    volumes:
      - ./backend/:/backend
    networks:
      - network
    environment:
      FLASK_ENV: development
    command: ["gunicorn", "-c", "gunicorn_config.py", "app:create_app()"]

  frontend:
    build:
      dockerfile: frontend.Dockerfile
      context: ./frontend
    container_name: react-frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
    networks:
      - network
    environment:
      NODE_ENV: development
    command: ["npm", "run", "deploy"]

networks:
  network: